# Generated by Django 4.2.11 on 2024-03-16 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_blogpost_city_comment_blogpost_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='accommodation_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='food_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
