# Generated by Django 4.2.11 on 2024-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_blogpost_accommodation_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='accommodation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='food',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
